# Generated by Django 2.2.1 on 2019-09-27 13:55

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='用户名')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='图像')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('gender', models.CharField(blank=True, max_length=4, null=True, verbose_name='性别')),
                ('address', models.TextField(blank=True, null=True, verbose_name='地址')),
            ],
            options={
                'verbose_name_plural': '作者',
                'verbose_name': '作者',
                'db_table': 'Author',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='类型名')),
                ('description', models.TextField(verbose_name='类型描述')),
            ],
            options={
                'verbose_name_plural': '类型',
                'verbose_name': '类型',
                'db_table': 'type',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='文章名')),
                ('date', models.DateField(auto_now=True, verbose_name='日期')),
                ('content', ckeditor.fields.RichTextField(verbose_name='文章内容')),
                ('description', ckeditor.fields.RichTextField(verbose_name='文章描述')),
                ('picture', models.ImageField(upload_to='images', verbose_name='图片')),
                ('recommend', models.IntegerField(default=0, verbose_name='推荐')),
                ('click', models.IntegerField(default=0, verbose_name='点击率')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Author.Author', verbose_name='作者')),
                ('type', models.ManyToManyField(to='Author.Type', verbose_name='类别')),
            ],
            options={
                'verbose_name_plural': '文章',
                'verbose_name': '文章',
                'db_table': 'article',
            },
        ),
    ]
