# Generated by Django 2.2.1 on 2019-09-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0002_auto_20190928_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.ImageField(default='images/1.jpg', upload_to='images', verbose_name='图片'),
        ),
    ]
