# Generated by Django 2.2.1 on 2019-09-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0003_auto_20190928_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.ImageField(upload_to='images', verbose_name='图片'),
        ),
    ]
