# Generated by Django 2.2.1 on 2019-09-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0004_auto_20190928_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(verbose_name='文章描述'),
        ),
    ]
