# Generated by Django 2.2.1 on 2019-09-28 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0006_auto_20190928_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='type',
        ),
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Author.Type', verbose_name='类别'),
        ),
    ]
